name: Update ETF CSV

on:

  schedule:

    # 台灣時間 18:00
    # 只跑星期一～星期五

    - cron: '0 10 * * 1-5'

  workflow_dispatch:

permissions:
  contents: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      # ====================================
      # Checkout Repo
      # ====================================

      - name: Checkout

        uses: actions/checkout@v4

        with:
          fetch-depth: 0

      # ====================================
      # Setup Python
      # ====================================

      - name: Setup Python

        uses: actions/setup-python@v5

        with:

          python-version: '3.11'

      # ====================================
      # Install Packages
      # ====================================

      - name: Install packages

        run: |

          pip install pandas
          pip install lxml
          pip install html5lib

      # ====================================
      # Run Python
      # ====================================

      - name: Run Python

        run: |

          python cketf13ok.py

      # ====================================
      # Commit CSV
      # ====================================

      - name: Commit CSV

        run: |

          git config --local user.email "action@github.com"

          git config --local user.name "github-actions"

          git add .

          git diff --quiet && git diff --staged --quiet || git commit -m "auto update csv"

          git push
